name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      PLATFORM: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Pack
        if: matrix.os != 'windows-latest'
        run: zip ./nrm_${{ matrix.os }}.zip ./target/release/nrm
      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.os != 'windows-latest'
        with:
          files: ./nrm_${{ matrix.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest'
        with:
          files: ./target/release/nrm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
